# Generated by Django 5.2.7 on 2025-10-20 14:18

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='encryption_key',
        ),
        migrations.AddField(
            model_name='conversation',
            name='encryption_key',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='static/profile.png', null=True, upload_to=users.models.upload_to),
        ),
    ]
